; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = featheresp32

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
monitor_speed = 115200
build_type = debug
build_flags = -Iinclude -Ilib/HAL/include -Ilib/Sensors/include -Ilib/Actuators/include -Ilib/UI/include -Ilib/Services/include -Ilib/Filters/include -Ilib/Controller/include -Ilib/Subsystems/include
lib_ldf_mode = deep+
lib_deps = 
	adafruit/DHT sensor library@^1.4.7
	adafruit/Adafruit NeoPixel@^1.15.5
	adafruit/Adafruit SSD1306@^2.5.17
	madhephaestus/ESP32Servo@^3.0.5

[env:native]
platform = native
test_framework = unity
test_build_src = yes
lib_ldf_mode = deep+
lib_deps = 
	Subsystems
build_flags = 
	-D UNIT_TEST
	-Iinclude
	-Itest
	-Ilib/HAL/include
	-Ilib/Sensors/include
	-Ilib/Actuators/include
	-Ilib/UI/include
	-Ilib/Services/include
	-Ilib/Filters/include
	-Ilib/Controller/include
	-Ilib/Subsystems/include
