; PlatformIO Project Configuration File

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
build_type = debug
build_flags = -Iinclude -Ilib/HAL/include -Ilib/Sensors/include -Ilib/Actuators/include -Ilib/UI/include -Ilib/Services/include -Ilib/Filters/include
lib_ldf_mode = chain+
lib_deps = 
	adafruit/DHT sensor library@^1.4.7
	adafruit/Adafruit NeoPixel@^1.15.5
	adafruit/Adafruit SSD1306@^2.5.17
	madhephaestus/ESP32Servo@^3.0.5

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_flags = 
	-D UNIT_TEST
	-Iinclude
	-Itest
	-Ilib/HAL/include
	-Ilib/Sensors/include
	-Ilib/Actuators/include
	-Ilib/UI/include
	-Ilib/Services/include
	-Ilib/Filters/include
